[package]
edition = "2021"
name = "loxlang-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_gc = []  # Enable GC debug output

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
clap = {version = "4.5.0", features = ["derive"]}
hashbrown = "0.14.3"
logos = "0.13.0"
regex = "1.10.3"
strum = {version = "0.26.1", features = ["derive"]}
thiserror = "1.0.56"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
datatest-stable = "0.3.3"
pretty_assertions = "1.4.0"
test-case = "3.3.1"

[[test]]
name = "lox_test_suite"
harness = false

[[bench]]
name = "binary_trees"
harness = false
